DROP TABLE users CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id int primary key generated by default as identity,
    username varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(100) not null,
    allows_data_access boolean NOT NULL
);

DROP TABLE IF EXISTS public.diary_entries;

CREATE TABLE IF NOT EXISTS public.diary_entries
(
    id int primary key generated by default as identity,
    user_id int not null,
    health_entry_id int,
    weather_entry_id int,
    created_at timestamp without time zone not null,
    entry_text varchar(1000),
    mood varchar(100),
    state_of_health varchar(100),
    activity_amount varchar(100)
)