DROP TABLE users;

CREATE TABLE IF NOT EXISTS users
(
    id int primary key generated by default as identity,
    username varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(100) not null,
    allows_data_access boolean NOT NULL
);